baseURL = 'https://xulinfeng.xyz/'
title = 'Linden'


languageCode = 'zh_cn'
timeZone = "Asia/Shanghai"

# ä¸»é¢˜
theme  =  "light-dark"
summaryLength = 140
hasCJKLanguage = true
# æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡ç”¨äºåˆ†é¡µ
paginate =  10
# rss è¾“å‡ºæ•°é‡
rssLimit = 5



[permalinks]
  posts = "/posts/:filename/"
  tags = "/tags/:slug/"

[menu]
  [[menu.main]]
    name="é¦–é¡µ"
    url="/"
    weight="1"

  [[menu.main]]
    name="å” å¨"
    url="/memos/"
    weight="2"
    
  [[menu.main]]
    name="å½’æ¡£"
    url="/archives/"
    weight="3"
  
  [[menu.main]]
    name="å…³äºæˆ‘"
    url="/about/"
    weight="4"
  
  [[menu.main]]
    name="ğŸ”"
    url="/search/"
    weight="5"



[params]
  subtitle = "ç”Ÿå‘½ä¸æ¯ï¼Œå¥‹æ–—ä¸æ­¢"
  description = "ç”Ÿå‘½å°±æ˜¯åé‡åŠ›çš„è¿‡ç¨‹"
	keywords = "åšå®¢ã€æŠ€æœ¯ã€ç”Ÿæ´»"

  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  
  # Enable to show reading time in minutes for posts
  showReadingTime = true

  Toc = true

  [params.author]
      name = "Linden"
  # umami ç»Ÿè®¡
  [params.umami]
    enable = true
    url = "https://u.xulinfeng.xyz/script.js"
    websiteId = "61dc66be-b6f9-4ae5-ac7b-fa5d68071ee0"

  [params.comment]
    enable = true
    [params.comment.twikoo]
      envId = "https://lindenxu-twikoo.hf.space"

[outputs]
  home = ["HTML","rss","json"] # <domain>/atom.xml
  

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"


