baseURL = 'https://xulinfeng.xyz/'
title = 'Linden'


languageCode = 'zh_cn'
timeZone = "Asia/Shanghai"

# ä¸»é¢˜
theme  =  "light-dark"
summaryLength = 140
hasCJKLanguage = true
# æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡ç”¨äºåˆ†é¡µ
paginate =  10
# rss è¾“å‡ºæ•°é‡
rssLimit = 5

# ç”Ÿæˆ robots.txt æ–‡ä»¶
enableRobotsTXT = true

[permalinks]
  [permalinks.page]
    posts = "/posts/:slugorfilename/"


[menus]
  [[menus.main]]
    name="é¦–é¡µ"
    url="/"
    weight="1"

  [[menus.main]]
    name="å” å¨"
    url="https://memo.xulinfeng.xyz"
    weight="2"
    [menus.main.params]
      blank="_blank"

  [[menus.main]]
    name="å½’æ¡£"
    url="/archives/"
    weight="3"
  
  [[menus.main]]
    name="å…³äºæˆ‘"
    url="/about/"
    weight="4"
  
  [[menus.main]]
    name="ğŸ”"
    url="/search/"
    weight="5"



[params]
  subtitle = "ç”Ÿå‘½ä¸æ¯ï¼Œå¥‹æ–—ä¸æ­¢"
  description = "ç”Ÿå‘½å°±æ˜¯åé‡åŠ›çš„è¿‡ç¨‹"
	keywords = "åšå®¢,æŠ€æœ¯,ç”Ÿæ´»"

  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  
  # Enable to show reading time in minutes for posts
  showReadingTime = true

  Toc = true

  [params.author]
      name = "Linden"
  # umami ç»Ÿè®¡
  [params.umami]
    enable = true
    url = "https://u.xulinfeng.xyz/script.js"
    websiteId = "c63e7b77-0f23-47a0-b7e1-bd98c0fbbf20"

  [params.comment]
    enable = true
    [params.comment.twikoo]
      envId = "https://tk.xulinfeng.xyz/"


[outputs]
  home = ["HTML","rss","json"] # <domain>/atom.xml
  

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"


