baseURL = 'https://xulinfeng.xyz/'
title = 'Linden'


languageCode = 'zh_cn'

# ä¸»é¢˜
theme  =  "light-dark"

# rss è¾“å‡ºæ•°é‡
rssLimit = 5



[permalinks]
  posts = "/posts/:filename/"
  tags = "/tags/:slug/"

[menu]
  [[menu.main]]
    name="é¦–é¡µ"
    url="/"
    weight="1"

  [[menu.main]]
    name="å” å¨"
    url="/memos/"
    weight="2"
    
  [[menu.main]]
    name="å½’æ¡£"
    url="/archives/"
    weight="3"
  
  [[menu.main]]
    name="å…³äºæˆ‘"
    url="/about/"
    weight="4"
  
  [[menu.main]]
    name="ğŸ”"
    url="/search/"
    weight="5"



[params]
  subtitle = "ä¸é—®æ˜å¤©ï¼Œæ‚ ç„¶æµªè´¹"
  description = "ç”Ÿå‘½å°±æ˜¯åé‡åŠ›çš„è¿‡ç¨‹"
	keywords = "åšå®¢ã€appã€æŠ˜è…¾ã€ç”Ÿæ´»ã€é˜…è¯»ã€è‡ªå¾‹"

  [params.author]
      name = "Linden"
 
  [params.comment]
    enable = true
    [params.comment.twikoo]
      envId = "https://lindenxu-twikoo.hf.space"

    
[outputs]
  home = ["HTML","rss","json"] # <domain>/atom.xml
  

[taxonomies]
category = "categories"
tag = "tags"
series = "series"


