baseURL = 'https://xulinfeng.xyz/'
title = 'Linden'
subtitle = "ä¸é—®æ˜å¤©ï¼Œæ‚ ç„¶æµªè´¹"

languageCode = 'zh_cn'

# ä¸»é¢˜
theme  =  "light-dark"
summaryLength = 140
hasCJKLanguage = true
# æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡ç”¨äºåˆ†é¡µ
paginate =  10
# rss è¾“å‡ºæ•°é‡
rssLimit = 5

[Author]
  name = "Linden"

[permalinks]
  posts = "/posts/:filename/"
  tags = "/tags/:slug/"

[menu]
  [[menu.main]]
    name="é¦–é¡µ"
    url="/"
    weight="1"

  [[menu.main]]
    name="å” å¨"
    url="/memos/"
    weight="2"
    
  [[menu.main]]
    name="å½’æ¡£"
    url="/archives/"
    weight="3"
  
  [[menu.main]]
    name="å…³äºæˆ‘"
    url="/about/"
    weight="4"
  
  [[menu.main]]
    name="ğŸ”"
    url="/search/"
    weight="5"



[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Enable to show reading time in minutes for posts
  showReadingTime = true
  DateFormatList = "2006-01-02"
  
  description = "ç”Ÿå‘½å°±æ˜¯åé‡åŠ›çš„è¿‡ç¨‹"
	keywords = "åšå®¢ã€appã€æŠ˜è…¾ã€ç”Ÿæ´»ã€é˜…è¯»ã€è‡ªå¾‹"
 
  [params.comment]
    enable = true
    [params.comment.twikoo]
      envId = "https://lindenxu-twikoo.hf.space"

  [params.footer]
    since = 2023
    poweredby = true


# è¯¦ç»†é…ç½®ï¼šhttps://gohugo.io/getting-started/configuration-markup/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
    
[outputs]
  home = ["HTML","rss","json"] # <domain>/atom.xml
  

[taxonomies]
category = "categories"
tag = "tags"
series = "series"


